"""
app/models/brief.py — Pydantic schema for GPT-4o SafetyBrief output validation.
"""

from typing import List, Literal

from pydantic import BaseModel, Field


class SafetyBriefOutput(BaseModel):
    """
    SafetyBrief output schema with LLM-generated content and metadata.

    Fields:
        brief_text: Narrative safety assessment (GPT-4o generated).
        key_findings: Bulleted list of critical findings (GPT-4o generated).
        pmids_cited: PubMed IDs cited in the brief (from Agent 2 retrieval).
        search_queries: PubMed search queries generated by Agent 1 (GPT-4o).
        recommended_action: Regulatory action recommendation (GPT-4o generated).
        drug_key: Drug name (normalized via RxNorm).
        pt: MedDRA preferred term for adverse reaction.
        stat_score: Statistical evidence score [0.0, 1.0] (deterministic).
        lit_score: Literature evidence score [0.0, 1.0] (deterministic).
        priority: Priority tier (P1-P4) based on score matrix (rule-based).
        generated_at: ISO timestamp of brief generation.
    """
    brief_text        : str
    key_findings      : List[str]
    pmids_cited       : List[str]
    search_queries    : List[str] = Field(
        min_length=1,
        max_length=5,
        description="Agent 1 generated search queries (typically 3)"
    )
    recommended_action: Literal["MONITOR", "LABEL_UPDATE", "RESTRICT", "WITHDRAW"]
    drug_key          : str
    pt                : str
    stat_score        : float = Field(ge=0.0, le=1.0)
    lit_score         : float = Field(ge=0.0, le=1.0)
    priority          : Literal["P1", "P2", "P3", "P4"]
    generated_at      : str
